//
// Created by tjrumoro on 4/3/22.
//

#ifndef RUMORO_THERESA_SLEEP_WALK_APP_INDIVIDUAL_H
#define RUMORO_THERESA_SLEEP_WALK_APP_INDIVIDUAL_H


class individual {

};


#endif //RUMORO_THERESA_SLEEP_WALK_APP_INDIVIDUAL_H
